# Generated by Django 2.2.5 on 2021-01-22 04:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210120_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 4, 54, 52, 566611, tzinfo=utc)),
        ),
    ]
